[pytest]
testpaths = tests

markers = 
    get_bookings: mark test as get_bookings
    get_booking: mark test as a get_booking
    post_booking: mark test as a post_booking
    put_booking: mark test as put_booking
    delete_booking: mark test as delete_booking
    smoke: mark test as smoke
    