[pytest]
testpaths = tests

markers = 
    get_bookings: mark test as get_bookings
    get: mark test as a get
    post: mark test as post
    put: mark test as put_booking
    delete_booking: mark test as delete_booking
    auth: mark test as auth
    login: mark test as login
    smoke: mark test as smoke
    api: mark test as api
    ui: mark test as ui
    login: mark test as login
    create_booking: mark test as create_booking
    bookings: mark test as bookings
    hybrid: mark test as hybrid
    booking: mark test as booking
    create: mark test as create
    error: mark test as error
    delete: mark test as delete
    