name: Run API Booking DELETE and PUT Tests

on:
  push:
    branches: [ fix/api-delete-update ]
  pull_request:
    branches: [ fix/api-delete-update ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Docker
        run: docker --version

      - name: Build containers
        run: docker compose build

      - name: start services
        run: docker compose up -d

      - name: Wait for backend
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8000 || sleep 3
          done

      - name: Run tests
        run: docker compose run --rm tests pytest -m "api and delete or api and put"

      - name: Shut down
        run: docker compose down