name: External Runner from Test Site

on:
  workflow_dispatch:
    inputs:
      suite:
        description: "Test suite"
        required: true
        type: choice
        options:
          - all
          - smoke
          - api
          - ui
          - hybrid

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Docker
        run: docker --version

      - name: Build containers
        run: docker compose build

      - name: start services
        run: docker compose up -d

      - name: Wait for backend
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8000 || sleep 3
          done

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.suite }}" = "smoke" ]; then
            docker compose run --rm tests pytest -m smoke
          elif [ "${{ github.event.inputs.suite }}" = "api" ]; then
            docker compose run --rm tests pytest -m api
          elif [ "${{ github.event.inputs.suite }}" = "ui" ]; then
            docker compose run --rm tests pytest -m ui
          elif [ "${{ github.event.inputs.suite }}" = "hybrid" ]; then
            docker compose run --rm tests pytest -m hybrid
          else
            docker compose run --rm tests pytest
          fi

      - name: Shut down
        run: docker compose down
